apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-prod
  namespace: argocd
spec:
  project: helm-gitops-project
  source:
    repoURL: https://github.com/Atreus27/Advanced-puzzle.git
    targetRevision: HEAD
    path: helm-gitops-project/charts/application
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: application-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
