apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "application.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default "nginx" }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.ingress.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "application.fullname" $ }}
                port:
                  number: {{ $.Values.service.port | default 5000 }}
    {{- end }}
