apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  namespace: {{ .Values.Namespace | default .Release.Namespace }}
data:
  nginx.conf: |
    server {
        listen 5000;
        root /usr/share/nginx/html;
        index index.html index.htm;

        # Health check endpoint
        location = / {
            return 200;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
