apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname" . }}
  namespace: {{ .Values.Namespace | default .Release.Namespace }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 5000 }}
      targetPort: {{ .Values.service.port | default 5000 }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "application.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
